# Generated by Django 4.2.23 on 2025-07-21 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título de la acción')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('duracion_minutos', models.PositiveIntegerField(default=30, verbose_name='Duración (minutos)')),
                ('tipo', models.CharField(choices=[('entrevista', 'Entrevista'), ('llamada', 'Llamada'), ('recordatorio', 'Recordatorio'), ('entrega', 'Entrega'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de acción')),
                ('finished', models.BooleanField(default=False, verbose_name='Finalizada')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
            ],
            options={
                'verbose_name': 'Acción de Agenda',
                'verbose_name_plural': 'Acciones de Agenda',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('mensaje_personalizado', models.TextField(blank=True, null=True, verbose_name='Mensaje personalizado')),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de aplicación')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.CreateModel(
            name='StatusMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de Candidatura')),
                ('mensaje', models.TextField(verbose_name='Plantilla de Mensaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_templates', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (Headhunter)')),
            ],
            options={
                'verbose_name': 'Plantilla de Mensaje de Estado',
                'verbose_name_plural': 'Plantillas de Mensajes de Estado',
                'unique_together': {('user', 'estado')},
            },
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Oferta de Empleo', 'verbose_name_plural': 'Ofertas de Empleo'},
        ),
        migrations.AddField(
            model_name='joboffer',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Beneficios'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers_created', to=settings.AUTH_USER_MODEL, verbose_name='Creada por'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='modality',
            field=models.CharField(choices=[('remote', 'Remoto'), ('onsite', 'Presencial'), ('hybrid', 'Híbrido')], default='onsite', max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary',
            field=models.CharField(blank=True, max_length=100, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del puesto'),
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.AddField(
            model_name='candidatura',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer', verbose_name='Oferta de Empleo'),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_applications', to=settings.AUTH_USER_MODEL, verbose_name='Candidato'),
        ),
        migrations.AddField(
            model_name='agendaaccion',
            name='oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_agendadas', to='jobs.joboffer', verbose_name='Oferta asociada'),
        ),
        migrations.AddField(
            model_name='agendaaccion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_acciones', to=settings.AUTH_USER_MODEL, verbose_name='Realizada por'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together={('offer', 'user')},
        ),
        migrations.AddIndex(
            model_name='agendaaccion',
            index=models.Index(fields=['user'], name='jobs_agenda_user_id_c4903d_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaaccion',
            index=models.Index(fields=['fecha_hora_inicio'], name='jobs_agenda_fecha_h_8d5c13_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaaccion',
            index=models.Index(fields=['oferta'], name='jobs_agenda_oferta__ffd9c5_idx'),
        ),
    ]
