# Generated by Django 5.2.3 on 2025-07-18 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_remove_joboffer_headhunter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oferta",
            name="user",
        ),
        migrations.AlterField(
            model_name="agendaaccion",
            name="oferta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agenda_acciones_oferta",
                to="jobs.joboffer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidatura",
            unique_together={("offer", "user")},
        ),
        migrations.AddField(
            model_name="candidatura",
            name="mensaje_inicial",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="accionoferta",
            name="realizada_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acciones_realizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agendaaccion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agenda_acciones_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="candidatura",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidaturas_usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="JobApplication",
        ),
        migrations.DeleteModel(
            name="Oferta",
        ),
        migrations.RemoveField(
            model_name="candidatura",
            name="fecha_aplicacion",
        ),
        migrations.RemoveField(
            model_name="candidatura",
            name="mensaje_personalizado",
        ),
    ]
