# Generated by Django 4.2.23 on 2025-07-21 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_agendaaccion_candidatura_statusmessagetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaaccion',
            name='candidatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_agendadas_candidatura', to='jobs.candidatura', verbose_name='Candidatura asociada'),
        ),
        migrations.AddIndex(
            model_name='agendaaccion',
            index=models.Index(fields=['candidatura'], name='jobs_agenda_candida_74da17_idx'),
        ),
    ]
